name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Set up PNPM
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Clone Web-K
      - name: Clone Web-K
        run: git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/morethanwords/tweb.git web-k

      # Clone Web-A
      - name: Clone Web-A
        run: git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/Ajaxy/telegram-tt.git web-a

      # Install dependencies Web-K
      - name: Install dependencies Web-K
        working-directory: web-k
        run: |
          pnpm install

      # Install dependencies
      - name: Install dependencies Web-A
        working-directory: web-a
        run: npm install

      # Apply custom patches
      - name: Apply code patches
        run: node patcher.js

      # Build Web-K
      - name: Build Web-K
        working-directory: web-k
        run: node build
        env:
          VITE_API_ID: 2496
          VITE_API_HASH: "8da85b0d5bfe62527e5b244c209159c3"
          VITE_PUSH_SERVER_KEY: "BHEbKOXt-GD8MCTTYiAYT3I5R4MB0epIE7Tbbymj1uR0xJRE_7m27eXTVAC_P19TeZnO9413lRz-0oZ87JRPKPM"

      # Build Web-A
      - name: Build Web-A
        working-directory: web-a
        run: npm run build:production
        env:
          BASE_URL: "https://gram.purrfectfarmer.com/a/"
          TELEGRAM_API_ID: 2496
          TELEGRAM_API_HASH: "8da85b0d5bfe62527e5b244c209159c3"

        # Move dist folder
      - name: Copy Dist
        run: |
          mkdir dist
          mv web-k/public dist/k
          mv web-a/dist dist/a

      # Upload the built files to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
